-- MySQL Script generated by MySQL Workbench
-- Tue Oct 21 21:15:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Project_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Project_DB` ;

-- -----------------------------------------------------
-- Schema Project_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Project_DB` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Project_DB` ;

-- -----------------------------------------------------
-- Table `Project_DB`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_DB`.`USERS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Project_DB`.`USERS` (
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Project_DB`.`DESTINATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_DB`.`DESTINATIONS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Project_DB`.`DESTINATIONS` (
  `destination_id` INT NOT NULL,
  `destination_name` VARCHAR(100) NULL,
  `country` TEXT NULL,
  `destination_description` VARCHAR(100) NULL,
  PRIMARY KEY (`destination_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Project_DB`.`TRIPS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_DB`.`TRIPS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Project_DB`.`TRIPS` (
  `trip_id` INT NOT NULL,
  `trip_name` VARCHAR(100) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `total_budget` DECIMAL(10,2) NULL,
  `total_expenses` DECIMAL(10,2) NULL,
  `user_id_fk` INT NOT NULL,
  PRIMARY KEY (`trip_id`),
  CONSTRAINT `fk_TRIPS_USERS`
    FOREIGN KEY (`user_id_fk`)
    REFERENCES `Project_DB`.`USERS` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TRIPS_USERS_idx` ON `Project_DB`.`TRIPS` (`user_id_fk` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Project_DB`.`ITINERARIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_DB`.`ITINERARIES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Project_DB`.`ITINERARIES` (
  `itinerary_id` INT NOT NULL,
  `day_number` INT NULL,
  `activities` TEXT NULL,
  `itinerary_notes` TEXT NULL,
  `trip_id_fk` INT NOT NULL,
  `destination_id_fk` INT NOT NULL,
  PRIMARY KEY (`itinerary_id`),
  CONSTRAINT `fk_ITINERARIES_TRIPS1`
    FOREIGN KEY (`trip_id_fk`)
    REFERENCES `Project_DB`.`TRIPS` (`trip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITINERARIES_DESTINATIONS1`
    FOREIGN KEY (`destination_id_fk`)
    REFERENCES `Project_DB`.`DESTINATIONS` (`destination_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ITINERARIES_TRIPS1_idx` ON `Project_DB`.`ITINERARIES` (`trip_id_fk` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_ITINERARIES_DESTINATIONS1_idx` ON `Project_DB`.`ITINERARIES` (`destination_id_fk` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Project_DB`.`WEATHERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_DB`.`WEATHERS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Project_DB`.`WEATHERS` (
  `weather_id` INT NOT NULL,
  `tempreature` DECIMAL(5,2) NULL,
  `description` VARCHAR(100) NULL,
  `humidity` INT NULL,
  `wind_speed` DECIMAL(5,2) NULL,
  `date_observed` DATE NULL,
  `weather_source` VARCHAR(50) NULL,
  `destination_id_fk` INT NOT NULL,
  PRIMARY KEY (`weather_id`),
  CONSTRAINT `fk_WEATHERS_DESTINATIONS1`
    FOREIGN KEY (`destination_id_fk`)
    REFERENCES `Project_DB`.`DESTINATIONS` (`destination_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_WEATHERS_DESTINATIONS1_idx` ON `Project_DB`.`WEATHERS` (`destination_id_fk` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Project_DB`.`ROUTES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_DB`.`ROUTES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Project_DB`.`ROUTES` (
  `route_id` INT NOT NULL,
  `distance` DECIMAL(6,2) NULL,
  `travel_time` VARCHAR(50) NULL,
  `route_source` VARCHAR(50) NULL,
  `trip_id_fk` INT NOT NULL,
  `origin_destination_id_fk` INT NOT NULL,
  `end_destination_id_fk` INT NOT NULL,
  PRIMARY KEY (`route_id`),
  CONSTRAINT `fk_ROUTES_TRIPS1`
    FOREIGN KEY (`trip_id_fk`)
    REFERENCES `Project_DB`.`TRIPS` (`trip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROUTES_DESTINATIONS1`
    FOREIGN KEY (`origin_destination_id_fk`)
    REFERENCES `Project_DB`.`DESTINATIONS` (`destination_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROUTES_DESTINATIONS2`
    FOREIGN KEY (`end_destination_id_fk`)
    REFERENCES `Project_DB`.`DESTINATIONS` (`destination_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ROUTES_TRIPS1_idx` ON `Project_DB`.`ROUTES` (`trip_id_fk` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_ROUTES_DESTINATIONS1_idx` ON `Project_DB`.`ROUTES` (`origin_destination_id_fk` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_ROUTES_DESTINATIONS2_idx` ON `Project_DB`.`ROUTES` (`end_destination_id_fk` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Project_DB`.`EXPENSES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_DB`.`EXPENSES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Project_DB`.`EXPENSES` (
  `expense_id` INT NOT NULL,
  `expense_description` VARCHAR(100) NULL,
  `expense_amount` DECIMAL(10,2) NULL,
  `exchange_rate` DECIMAL(10,4) NULL,
  `itinerary_id_fk` INT NOT NULL,
  `destination_id_fk` INT NOT NULL,
  PRIMARY KEY (`expense_id`),
  CONSTRAINT `fk_EXPENSES_ITINERARIES1`
    FOREIGN KEY (`itinerary_id_fk`)
    REFERENCES `Project_DB`.`ITINERARIES` (`itinerary_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EXPENSES_DESTINATIONS1`
    FOREIGN KEY (`destination_id_fk`)
    REFERENCES `Project_DB`.`DESTINATIONS` (`destination_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_EXPENSES_ITINERARIES1_idx` ON `Project_DB`.`EXPENSES` (`itinerary_id_fk` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_EXPENSES_DESTINATIONS1_idx` ON `Project_DB`.`EXPENSES` (`destination_id_fk` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Project_DB`.`RATES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_DB`.`RATES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Project_DB`.`RATES` (
  `user_id_fk` INT NOT NULL,
  `destination_id_fk` INT NOT NULL,
  `rate_id` INT NOT NULL,
  `favorite` TINYINT NULL,
  `rating` INT NULL,
  PRIMARY KEY (`rate_id`),
  CONSTRAINT `fk_USERS_has_DESTINATIONS_USERS1`
    FOREIGN KEY (`user_id_fk`)
    REFERENCES `Project_DB`.`USERS` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_has_DESTINATIONS_DESTINATIONS1`
    FOREIGN KEY (`destination_id_fk`)
    REFERENCES `Project_DB`.`DESTINATIONS` (`destination_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_USERS_has_DESTINATIONS_DESTINATIONS1_idx` ON `Project_DB`.`RATES` (`destination_id_fk` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_USERS_has_DESTINATIONS_USERS1_idx` ON `Project_DB`.`RATES` (`user_id_fk` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
