version: "3.9"
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      MONGODB_URI: "mongodb://mongo:27017/travelplanner"
      JWT_SECRET: "devsecret"
      NOMINATIM_USER_AGENT: "travel-planner-demo/1.0 (contact: you@example.com)"
    depends_on:
      - mongo
